#!/usr/bin/env node

/**
 * post-process.mjs
 *
 * 将 Luban 导出的 JSON 数据内联为 TypeScript，并交给 Luban 生成的 Tables 统一管理。
 *
 * 设计要点（为什么不再自己生成 List/Map/get）：
 *   Luban 的 schema.ts 已经生成了完整的表管理层——每张表的 TbXxx（含正确主键的 Map、
 *   get()、跨表引用 resolve()）以及顶层 Tables 管理类。Tables 通过一个 JsonLoader
 *   `(file) => 该表的 JSON 数组` 加载全部数据并解析引用。本脚本要做的仅仅是：
 *     1) 把每个 <table>.json 原样内联成 TS（snake_case 不变，正是 TbXxx 期望的输入）；
 *     2) 生成 index.ts：把所有表汇总为导出的 RAW（表名 → 数据）。
 *   Tables 的实例化与 ServiceLocator 注册不在生成物里，由 game 侧手写的 GameTables
 *   （extends Tables implements IService）负责，其 JsonLoader 从 RAW 取数。这样主键/
 *   类名/驼峰/引用等全部由 Luban 负责，脚本不再猜测，从根上消除此前那几类 bug。
 *
 * 用法: node post-process.mjs <json_dir> <output_dir>
 * 示例: node post-process.mjs export_json ../map/src/game/data/data_tables
 *
 * 业务侧使用（经 ServiceLocator 取全局 GameTables）：
 *   import { locator } from 'libs/service/ServiceLocator';
 *   import { GameTables } from 'game/data/GameTables';
 *   const scene = locator.get(GameTables).TbSceneConfig.get(1);
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, basename } from 'path';

// 解析命令行参数
const args = process.argv.slice(2);
if (args.length < 2) {
    console.error('用法: node post-process.mjs <json_dir> <output_dir>');
    console.error('示例: node post-process.mjs export_json ../map/src/game/data/data_tables');
    process.exit(1);
}
const [jsonDir, outputDir] = args;

const HEADER =
    `//------------------------------------------------------------------------------\n` +
    `// 自动生成的数据 - 请勿手动修改 (Generated by post-process.mjs)\n` +
    `//------------------------------------------------------------------------------\n\n`;

// 读取 JSON 目录下所有 .json，返回 { 表名: 数据数组 }
function loadJsonFiles(dir) {
    const jsonData = {};
    for (const file of readdirSync(dir)) {
        if (!file.endsWith('.json')) continue;
        const filePath = join(dir, file);
        if (!statSync(filePath).isFile()) continue;
        jsonData[basename(file, '.json')] = JSON.parse(readFileSync(filePath, 'utf-8'));
    }
    return jsonData;
}

// 主流程
try {
    console.log(`读取 JSON 数据: ${jsonDir}`);
    const jsonData = loadJsonFiles(jsonDir);
    const tableNames = Object.keys(jsonData);

    if (tableNames.length === 0) {
        console.error('错误: 未找到任何 JSON 文件');
        process.exit(1);
    }
    console.log(`找到 ${tableNames.length} 个表: ${tableNames.join(', ')}`);

    // 1) 每张表一个文件：原样内联 JSON 数组（snake_case 不变，供 Luban 的 TbXxx 消费）
    for (const name of tableNames) {
        let ts = HEADER;
        ts += `/** ${name} 原始配置数据（snake_case，直接喂给 Luban 的 Tables/TbXxx） */\n`;
        ts += `export const ${name}: any[] = ${JSON.stringify(jsonData[name], null, 4)};\n`;
        writeFileSync(join(outputDir, `${name}.ts`), ts, 'utf-8');
        console.log(`  生成: ${name}.ts (${jsonData[name].length} 行)`);
    }

    // 2) index.ts：注册所有表到 JsonLoader + 创建【唯一的全局 Tables 实例】
    const sorted = [...tableNames].sort();
    let idx = HEADER;
    for (const name of sorted) {
        idx += `import { ${name} } from './${name}';\n`;
    }
    idx += `\n/**\n`;
    idx += ` * 表名 → 原始 JSON 数据（snake_case）。\n`;
    idx += ` * 仅汇总数据，不在此实例化 Tables；实例化与 ServiceLocator 注册由 game 侧\n`;
    idx += ` * 的 GameTables（extends Tables implements IService）负责，其 JsonLoader 按名\n`;
    idx += ` * 从 RAW 返回。TSTL 会把 RAW 编译进 Lua，无需运行时读文件。\n`;
    idx += ` */\n`;
    idx += `export const RAW: { [file: string]: any[] } = {\n`;
    for (const name of sorted) {
        idx += `    ${name},\n`;
    }
    idx += `};\n`;
    writeFileSync(join(outputDir, 'index.ts'), idx, 'utf-8');
    console.log(`  生成: index.ts (RAW 汇总, ${sorted.length} 张表)`);

    console.log(`\n生成完成! 共 ${tableNames.length} 个数据表 + 1 个 index.ts（RAW 汇总）`);
} catch (error) {
    console.error('错误:', error.message);
    console.error(error.stack);
    process.exit(1);
}
